name: CI
on:
  push:
  pull_request:
    branches:
      - master
    types: 
      - ready_for_review
      - review_requested


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          cache: gradle
      - name: Build with Gradle
        run: ./gradlew build
